#ifndef SETSGLOBALES_H
#define SETSGLOBALES_H

#define PIXELTOMETER 20
#define PADDLE_SPEED (-15)
#define PADDLE_MAX_ANGLE 0.6
#define PADDLE_MIN_ANGLE (-0.4) 
#define MAX_VELOCITY_X 30
#define MAX_VELOCITY_Y 30

#endif 